Sprint 2/step 2
NKolosov097/react-burger pull request #2
Opened 2023-03-25 22:29 UTC by NKolosov097

2023-03-26 04:13 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/9lsfMkBRyBs9BQ> - У вас шрифт слетел;

- Нужно запретить нажатие кнопки, если пользователь не выбрал ничего или выбрал только ингредиенты <https://disk.yandex.com/i/9PKllrZjWPgNqQ>;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/PqP-Z66ZcmkCrQ>;

- По чек листу требуется реализовать: При скролле внутри компонента BurgerIngredients самый ближний к верхней левой границе заголовок контейнера становится активным;

- Поправьте расширения файлов, а то у вас в разброс, какие-то имеют `jsx`, а какие-то `js`, хотя должны быть тоже `jsx`.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили. Проверьте во всём проекте;

- У вас не должно быть в коде eslint-disable, без крайней необходимости, не стоит его использовать; Проверьте во всём проекте;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-26 04:13 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-item/ingredient-item.jsx
> +            },
**Рекомендую исправить:**

Лучше передавать цельный объект ингредиента, а не отдельные его поля;

2023-03-26 04:13 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-item/ingredient-item.jsx
> +        typeOfIngredient === 'bun'
**Надо исправить:**

Используйте тут обычные `if/else` условия, а не тернарные операторы.

2023-03-26 04:13 UTC, ArslanDev666 commented on src/services/reducers/ingredients-reducer.js
> +        }
**Надо исправить:**

у вас не должно быть в коде `eslint-disable`, без крайней необходимости, не стоит его использовать

2023-03-26 04:13 UTC, ArslanDev666 commented on src/services/reducers/modal-details-reducer.js
> +    infoOfIngredient: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-03-26 04:13 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                    <ModalOverlay />
**Надо исправить:**

`ModalOverlay` и вся логика связанныая с модальными окнами, должны находится в компоненте `Modal`;

2023-03-26 15:42 UTC, NKolosov097 commented on src/components/burger-constructor/bun/bun.js
> +                    text={bun?.name}
здесь я реализовал эту приписку с помощью пропса coordinate, которая подсказывает как нужно отрисовать блок. этот промис равен или top, или bottom

2023-03-26 15:45 UTC, NKolosov097 commented on src/components/burger-constructor/burger-constructor.jsx
> +                    <ModalOverlay />
не исправил только этот момент, так как не до конца понимаю почему нужно это делать? в прошлом спринте говорилось, что есть компонент Modal и есть компонент ModalOverlay, который должен отрисовываться сразу после Modalб Нужно просто создать еще один компонент, который будет их объединять?

2023-03-27 05:36 UTC, ArslanDev666 commented on src/components/burger-constructor/bun/bun.js
> +                    text={bun?.name}
Это понятно, но надписей всё равно не видно, https://disk.yandex.com/i/joVstM9XsREmqQ

2023-03-27 05:42 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                    <ModalOverlay />
Зачем создавать дополнительный компонент, если это всё можно сделать в компоненте `modal`? 

Да и если подумать немного, то `modalOverlay` - это в любом случае часть модального окна. Так почему бы это всё не сделать вместе)) 

```js
// Modal.jsx;

...

return (
  <>
    <div className={styles.modal}>...</div>
    <ModalOverlay onClose={onClose} />
  </>
) 
```

А по поводу логики, то вот пункт из чек-листа.

https://disk.yandex.com/i/_fa9gxvTYhDxWA

2023-03-27 05:53 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/9lsfMkBRyBs9BQ> - У вас шрифт слетел;

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили. Проверьте во всём проекте. Всё ещё остались инлайн стили: <https://disk.yandex.com/i/OuPnSmg7UfBT6A>;

- В некоторых местах вместо `propTypes` указано `prototype`

2023-03-27 05:53 UTC, ArslanDev666 commented on src/components/burger-constructor/ingredients-list-in-constructor/ingredients-list.jsx
> +    ).isRequired,
Замечание: https://github.com/NKolosov097/react-burger/pull/2#discussion_r1148471219 - не исправлено.

2023-03-27 05:53 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-item/ingredient-item.jsx
>  IngredientItem.prototype = {
**Надо исправить:**

вместо `propTypes` указано `prototype`

2023-03-27 05:53 UTC, ArslanDev666 commented on src/components/burger-constructor/bun/bun.jsx
> +Bun.prototype = {
**Надо исправить:**

вместо `propTypes` указано `prototype`

2023-03-27 05:53 UTC, ArslanDev666 commented on src/components/burger-constructor/ingredients-list-in-constructor/ingredients-list.jsx
> +IngredientsList.prototype = {
**Надо исправить:**

вместо `propTypes` указано `prototype`

2023-03-27 05:53 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-list/ingredient-list.jsx
>  IngredientList.prototype = {
**Надо исправить:**

вместо `propTypes` указано `prototype`

2023-03-27 05:53 UTC, ArslanDev666 commented on src/components/burger-constructor/assembling-burger/assembling-burger.jsx
> +    moveIngredients: PropTypes.func.isRequired,
**Надо исправить:**

чуть выше, вместо `propTypes` указано `prototype`

2023-03-28 03:28 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания были исправлены;

### **Сделает код лучше:**

- <https://disk.yandex.com/i/5D5y6HBXo7Mh4A> - У вас шрифт слетел;

2023-03-28 10:26 UTC, merged