Sprint 5/step 1
NKolosov097/react-burger pull request #5
Opened 2023-05-21 17:32 UTC by NKolosov097

2023-05-21 20:15 UTC, kyzinatra commented on src/App.tsx
>  import { ForgotPassword } from './pages/forgot-password/forgot-password'
Надо исправить: стоит добавить `key` и избавится от варна в консоли (скрин)

2023-05-21 20:16 UTC, kyzinatra commented on src/App.tsx
Надо исправить: по прямой ссылке `http://localhost:3000/feed/646a7b988a4b62001c83b0a0` не открывается модальное окно с заказом

2023-05-21 20:17 UTC, kyzinatra commented on src/App.tsx
> +
Надо исправить: при перезагрузки страницы выбрасывает из аккаунта, нужно поправить.

2023-05-21 20:17 UTC, kyzinatra commented on src/App.tsx
>      }, [dispatch])
Надо исправить: по аналогии модальные окна с заказами в профиле

2023-05-21 20:18 UTC, kyzinatra commented on src/pages/profile/orders/orders.tsx
> +        getUserData()(dispatch)
Надо исправить: сортировать заказы в профиле стоит по убыванию даты. Сейчас новые в самом конце.

2023-05-21 20:20 UTC, kyzinatra commented on src/services/middlewares/index.ts
> +                } else {
Надо исправить:
Необходимо добавить обработку эвента закрытия сокета `if (type === wsActions.wsClose)`, стоит закрывать сокет `ws.close()`, чтобы не получалась ситуация как на скрине, когда мы несколько раз зашли на страницу и у нас открылось очень много соединений с веб сокетами. 

Также было бы круто сделать какую-нибудь переменную выше в функции, которую при создания сокета мы бы ставили в `true`, а при закрытии по эвенту `wsClose` в `false`, так мы сможем проверять в `socket.onclose` что если она все еще true, значит произошла ошибка, и стоит попробовать переподключится к сокету еще раз.

2023-05-21 20:21 UTC, kyzinatra commented on src/services/middlewares/index.ts
> +                        `${WS_API}?token=${localStorage.getItem('accessToken')}`
Надо исправить: из-за strict mode сейчас сокет открывается 2 раза. Стоит поправить, чтобы так было сделать нельзя

2023-05-21 20:24 UTC, kyzinatra commented on src/services/reducers/index.ts
>      authReducer,
Отлично! Хорошая композиция редьюсеров

2023-05-21 20:24 UTC, kyzinatra commented on src/store.ts
> +    | TIngredientsAction
Хорошо, что вы сделали типы

2023-05-21 20:25 UTC, kyzinatra commented on src/store.ts
> +        )
Отлично! Хорошее использование middleware

2023-05-21 20:25 UTC, kyzinatra commented on src/pages/profile/profile.tsx
> +                                        password: form.password,
Можно лучше: мне кажется стоит вынести обработчик в отдельную функцию

2023-05-21 20:27 UTC, kyzinatra commented on src/pages/forgot-password/forgot-password.tsx
>              navigate('/reset-password')
Можно лучше: не стоит использовать ts-ignore - это очень плохой подход. Стоит поправить типы. localStorage не принимает boolean типы. Он все равно приведет его к строке `true`

2023-05-21 20:27 UTC, kyzinatra commented on src/services/middlewares/index.ts
> +
Отлично! Хорошая типизация сокета

2023-05-21 20:28 UTC, kyzinatra commented on src/services/reducers/WS-auth-reducer.ts
> +            }
Отлично! Хорошо, что вы описали все типы соединения для сокетов

2023-05-21 20:29 UTC, kyzinatra commented on src/pages/profile/profile.tsx
> +            name: user?.name ? user.name : '',
Можно лучше: такие условия можно писать проще `user?.email || ''`

2023-05-21 20:32 UTC, kyzinatra commented
Выглядит очень круто! Видно, что проделана большая работа. Но все же есть моменты на которые стоит обратить внимание. 
В целом сокеты сделаны очень хорошо. Немного поехали шрифты в названиях. Но очень круто, что вы внимательно подошли к работе и покрасили все состояния и обновляете их в режиме реального времени.
Подробнее: 

**Что важно исправить:**

-  стоит добавить key и избавится от варна в консоли (скрин)

-  по прямой ссылке `http://localhost:3000/feed/646a7b988a4b62001c83b0a0` не открывается модальное окно с заказом
-  при перезагрузки страницы выбрасывает из аккаунта, нужно поправить.
-  по аналогии модальные окна с заказами в профиле
-  сортировать заказы в профиле стоит по убыванию даты. Сейчас новые в самом конце.
- 
Необходимо добавить обработку эвента закрытия сокета `if (type === wsActions.wsClose)`, стоит закрывать сокет ws.close() и закрывать и открывать сокет только когда он нужен. То есть по заходу на страницу

Также было бы круто сделать какую-нибудь переменную выше в функции, которую при создания сокета мы бы ставили в true, а при закрытии по эвенту `wsClose `в false, так мы сможем проверять в socket.onclose что если она все еще true, значит произошла ошибка, и стоит попробовать переподключиться к сокету еще раз.
-  из-за strict mode сейчас сокет открывается 2 раза. Стоит поправить, чтобы так было сделать нельзя


**Можно лучше:**

-  мне кажется стоит вынести обработчик в отдельную функцию
-  не стоит использовать ts-ignore - это очень плохой подход. Стоит поправить типы. `localStorage` не принимает boolean типы. Он все равно приведет его к строке true
-  такие условия можно писать проще `user?.email || ''"`


**Что понравилось:**

-  Хорошая композиция редьюсеров
-  Хорошо, что вы сделали типы
-  Хорошее использование middleware
-  Хорошая типизация сокета
-  Хорошо, что вы описали все типы соединения для сокетов


**Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.**

2023-05-21 20:35 UTC, NKolosov097 commented
Спасибо большое Вам за ревью! :)

Мне явно не хватало четко структурированного списка с замечаниями, по которому я могу пройтись и все привести в порядок. Сегодня/завтра скину исправленную работу)




Sunday, May 21, 2023 at 23:32 +0300 from ***@***.***  ***@***.***>:
>Выглядит очень круто! Видно, что проделана большая работа. Но все же есть моменты на которые стоит обратить внимание.
>В целом сокеты сделаны очень хорошо. Немного поехали шрифты в названиях. Но очень круто, что вы внимательно подошли к работе и покрасили все состояния и обновляете их в режиме реального времени.
>Подробнее:
>Что важно исправить:
>* 
>стоит добавить key и избавится от варна в консоли (скрин)
>* 
>по прямой ссылке http://localhost:3000/feed/646a7b988a4b62001c83b0a0 не открывается модальное окно с заказом
>* 
>при перезагрузки страницы выбрасывает из аккаунта, нужно поправить.
>* 
>по аналогии модальные окна с заказами в профиле
>* 
>сортировать заказы в профиле стоит по убыванию даты. Сейчас новые в самом конце.
>* 
>Необходимо добавить обработку эвента закрытия сокета if (type === wsActions.wsClose), стоит закрывать сокет ws.close() и закрывать и открывать сокет только когда он нужен. То есть по заходу на страницу
>Также было бы круто сделать какую-нибудь переменную выше в функции, которую при создания сокета мы бы ставили в true, а при закрытии по эвенту wsClose в false, так мы сможем проверять в socket.onclose что если она все еще true, значит произошла ошибка, и стоит попробовать переподключиться к сокету еще раз.
>*  из-за strict mode сейчас сокет открывается 2 раза. Стоит поправить, чтобы так было сделать нельзя
>Можно лучше:
>*  мне кажется стоит вынести обработчик в отдельную функцию
>*  не стоит использовать ts-ignore - это очень плохой подход. Стоит поправить типы. localStorage не принимает boolean типы. Он все равно приведет его к строке true
>*  такие условия можно писать проще user?.email || ''"
>Что понравилось:
>*  Хорошая композиция редьюсеров
>*  Хорошо, что вы сделали типы
>*  Хорошее использование middleware
>*  Хорошая типизация сокета
>*  Хорошо, что вы описали все типы соединения для сокетов
>Обратите внимание, что работа принимается только после исправления всех «Надо исправить».
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <NKolosov097/react-burger/pull/5/c1556284585 @ github . com>

2023-05-21 21:21 UTC, NKolosov097 commented on src/services/middlewares/index.ts
> +                        `${WS_API}?token=${localStorage.getItem('accessToken')}`
Можете подсказать как это можно исправить? С помощью доп флага в редаксе?

2023-05-21 21:29 UTC, kyzinatra requested changes

2023-05-21 21:29 UTC, kyzinatra commented on src/services/middlewares/index.ts
> +                        `${WS_API}?token=${localStorage.getItem('accessToken')}`
Не в редаксе. Просто не нужно поднимать новый сокет, если еще или уже есть другой. Нужно либо закрыть старый либо игнорировать новый

2023-05-21 21:42 UTC, NKolosov097 commented on src/services/middlewares/index.ts
> +                        `${WS_API}?token=${localStorage.getItem('accessToken')}`
![image](https://github.com/NKolosov097/react-burger/assets/87139155/dfa63538-f27c-418d-a67a-8a659ce10f1e)

когда делаю дополнительную проверку на socket, то он не соединяется не при каком раскладе. Почему?

2023-05-21 21:45 UTC, NKolosov097 commented on src/services/middlewares/index.ts
> +                        `${WS_API}?token=${localStorage.getItem('accessToken')}`
там был мой затуп... Все поправил)

2023-05-23 18:22 UTC, kyzinatra commented
Вы отлично потрудились над правками. Почти все работает, но до сих пор сокет не закрывается, когда пользователь уходит со страницы `feed` (см скрин). Это нужно поправить. Вам необходимо вызывать `soket.close()` в момент когда нужно закрыть сокет.
![image](https://github.com/NKolosov097/react-burger/assets/51288221/4cdee016-7f65-47c1-b987-1a5939d62915)

2023-05-23 19:49 UTC, NKolosov097 commented
когда я добавляю эти три строчки, чтобы закрывать сокет при закрытии страницы, у меня заказы вообще не приходят
![image](https://github.com/NKolosov097/react-burger/assets/87139155/79d37a4f-c620-4eec-b753-a9a1e0b7c605)

просто висят в статусе finished
![image](https://github.com/NKolosov097/react-burger/assets/87139155/619e020b-8a90-4699-bb5f-aaf2b04404b0)

2023-05-23 19:53 UTC, kyzinatra commented
> когда я добавляю эти три строчки, чтобы закрывать сокет при закрытии страницы, у меня заказы вообще не приходят ![image](https://user-images.githubusercontent.com/87139155/240403134-79d37a4f-c620-4eec-b753-a9a1e0b7c605.png)
> 
> просто висят в статусе finished ![image](https://user-images.githubusercontent.com/87139155/240403256-619e020b-8a90-4699-bb5f-aaf2b04404b0.png)

Ну да, сокет при перезоходе закроется, это значит, что его нужно заново открыть. Используйте для этого useEffect

2023-05-23 19:56 UTC, NKolosov097 commented
> 

использовать useEffect в middleware? если Вы говорите использовать useEffect на странице заказа, то он у меня и так там есть
![image](https://github.com/NKolosov097/react-burger/assets/87139155/5d04e90a-510c-4217-b403-96e21db251d6)

2023-05-23 20:05 UTC, kyzinatra commented
> > 
> 
> использовать useEffect в middleware? если Вы говорите использовать useEffect на странице заказа, то он у меня и так там есть ![image](https://user-images.githubusercontent.com/87139155/240404705-5d04e90a-510c-4217-b403-96e21db251d6.png)

Да, я говорю про useEffect на странице. Если он у вас уже есть, то посмотрите почему сокет не открывается снова. Может быть вы забыли почистить что-то после закрытия. Почему сокет не открывается снова по dispatch в useEffect. Он же выполняется при заходе? Но сокет не открывается...

2023-05-25 16:50 UTC, kyzinatra commented
Работа отклоняется без потери итерации так как с предыдущей проверки новых коммитов не было. Возможно вы забыли запушить изменения.

2023-05-26 20:41 UTC, merged